### PR TITLE
Some minor updates

### PR DESCRIPTION
**Pull request by edgarmueller**
Most of these issues are linked to https://github.com/eclipsesource/jsonforms/issues/1166, the README might need to be updated once more if the 2.0.12 final release is available.

### CODE REVIEW

**Comment by edgarmueller** [comment]
I configured the linter and fixed the resulting warnings

**Comment by edgarmueller** [comment]
It's the default ionic linter setting.

**Comment by eneufeld** [comment]
I would suggest to merge this. We should go trough all linter settings anyway in the future and we can unify them then.

**Comment by edgarmueller** [comment]
Yes, it just has been pending because the proposed changes needed to 2.0.12 to be released first (which I did a couple of minutes ago).

**Pull request merged**
